# Generated by Django 2.2.4 on 2021-02-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiggleWinksApp', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='item_pics'),
        ),
    ]
